# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiloAppsKit < Formula
  desc "milo-apps-kit CLI — single-host PaaS client"
  homepage "https://github.com/callmemhz/milo-apps-kit"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/callmemhz/milo-apps-kit/releases/download/v0.1.0/milo-apps-kit_0.1.0_darwin_amd64.tar.gz"
      sha256 "f15ac3363451a90e7f2628b1f752cc33b873d0ef33a641bca21090df016582ae"

      define_method(:install) do
        bin.install "milo-apps-kit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/callmemhz/milo-apps-kit/releases/download/v0.1.0/milo-apps-kit_0.1.0_darwin_arm64.tar.gz"
      sha256 "289ad6ce8f61e90d1d15a6ff4d0c6e02fba6246663fa1682c0bf445794b5a208"

      define_method(:install) do
        bin.install "milo-apps-kit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/callmemhz/milo-apps-kit/releases/download/v0.1.0/milo-apps-kit_0.1.0_linux_amd64.tar.gz"
      sha256 "bf76035a4b435e35e070962378dae30d09f68f8e8706dd101f9d3997416df89b"
      define_method(:install) do
        bin.install "milo-apps-kit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/callmemhz/milo-apps-kit/releases/download/v0.1.0/milo-apps-kit_0.1.0_linux_arm64.tar.gz"
      sha256 "8686b768cb9a666b96863b96fed0d6943aa9db58039ad39157fc12f37c97e85e"
      define_method(:install) do
        bin.install "milo-apps-kit"
      end
    end
  end

  test do
    system "#{bin}/milo-apps-kit", "version"
  end
end
