# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Milo < Formula
  desc "milo CLI — single-host PaaS client"
  homepage "https://github.com/callmemhz/milo"
  version "0.5.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/callmemhz/milo/releases/download/v0.5.0/milo_0.5.0_darwin_amd64.tar.gz"
      sha256 "4bda54dbf4a2ef91ee13ad542972446c8b571aac4edbe9d5696881290dea544a"

      define_method(:install) do
        bin.install "milo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/callmemhz/milo/releases/download/v0.5.0/milo_0.5.0_darwin_arm64.tar.gz"
      sha256 "749c4f61f35dcc885af5f05e1fba154a9023c4fe1dc222fa12a7ff4f8735f741"

      define_method(:install) do
        bin.install "milo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/callmemhz/milo/releases/download/v0.5.0/milo_0.5.0_linux_amd64.tar.gz"
      sha256 "ae47f2ee9655dff82c31cb39b96835f66ca2b309bd9f82d2b34cec7f8265daa0"
      define_method(:install) do
        bin.install "milo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/callmemhz/milo/releases/download/v0.5.0/milo_0.5.0_linux_arm64.tar.gz"
      sha256 "692fa8dfc7533dbd4c498e3eeca270673021eb87a058e13064709fad54d0037a"
      define_method(:install) do
        bin.install "milo"
      end
    end
  end

  test do
    system "#{bin}/milo", "version"
  end
end
