# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiloAppsKit < Formula
  desc "milo-apps-kit CLI — single-host PaaS client"
  homepage "https://github.com/callmemhz/milo-apps-kit"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/callmemhz/milo-apps-kit/releases/download/v0.2.0/milo-apps-kit_0.2.0_darwin_amd64.tar.gz"
      sha256 "574f5835371d6aac72cd791feee7b4b78c25291db50d82c14f54eedfc756c164"

      define_method(:install) do
        bin.install "milo-apps-kit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/callmemhz/milo-apps-kit/releases/download/v0.2.0/milo-apps-kit_0.2.0_darwin_arm64.tar.gz"
      sha256 "0ca52f06d449dfc7384a17afd949802b039b4ed4f9fdeb9c6f5e0dab79d68ac4"

      define_method(:install) do
        bin.install "milo-apps-kit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/callmemhz/milo-apps-kit/releases/download/v0.2.0/milo-apps-kit_0.2.0_linux_amd64.tar.gz"
      sha256 "2339c57965abe72bf78e542073f66e721ab9f5c307596faffb3170a99a98feae"
      define_method(:install) do
        bin.install "milo-apps-kit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/callmemhz/milo-apps-kit/releases/download/v0.2.0/milo-apps-kit_0.2.0_linux_arm64.tar.gz"
      sha256 "29d298130df1ecda96b96f5ea6b939d918ab2371c6af44ab6f75d8a48ef1dc38"
      define_method(:install) do
        bin.install "milo-apps-kit"
      end
    end
  end

  test do
    system "#{bin}/milo-apps-kit", "version"
  end
end
